### ISSUE TITLE
Incorrect types for dispute and reportOutcome

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/tools#122]
`Market.reportOutcome` and `Market.dispute` both have the input property `outcome: number` it should be `outcome: OutcomeReport`

**Comment by saboonikhil** [comment]
I think it is in sync with https://github.com/zeitgeistpm/zeitgeist/blob/main/misc/types.json 

@sea212 @c410-f3r If anyone of you could review once?

**Comment by c410-f3r** [comment]
Not used to the internals of this project so maybe @sea212 can provide a better answer.

I do know that `outcome` used to be a numeric parameter for scalar markets but it is now an enum for different market types. Now, since `outcome: number` isn't representing the index representation of the upstream `OutcomeReport` enum, then `outcome` should be indeed mapped to a local TS `outcomeReport` representation.

**Comment by sea212** [comment]
It is in sync.

**Comment by Robiquet** [comment]
Seems like something is wrong, it doesn't work with a number. Maybe @lsaether can give a better explanation

**Comment by sea212** [comment]
> Seems like something is wrong, it doesn't work with a number. Maybe @lsaether can give a better explanation

What exactly does not work, where do you specify outcome as a number? I am a bit confused, because according to the SDK types, outcome does not represent a number but an enum (exactly as it is represented in the chain currently) https://github.com/zeitgeistpm/tools/blob/08275262a0705e2d78f6a28d89a57884dbf949d2/packages/type-defs/src/predictionMarkets.ts#L66-L71 .
The types in SDK and in the chain both point to `OutcomeReport` in the relevant places, they are identical.

**Comment by Robiquet** [comment]
Here: https://github.com/zeitgeistpm/tools/blob/08275262a0705e2d78f6a28d89a57884dbf949d2/packages/sdk/src/models/market.ts#L489 this function is typed to receive a number as an outcome when it actually need an OutcomeReport

**Comment by saboonikhil** [comment]
@Robiquet - with the latest changes in the main, this issue should be resolved. Could you please confirm?
