### ISSUE TITLE
createNewMarket arguments

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/tools#27]
If createNewMarket function gets changed in future please consider using options object instead of individual arguments:

e.g. something like `createNewMarket(signer, title, options)` instead of `createNewMarket([endless list of arguments])`.

**Comment by morkeltry** [comment]
This change was implemented but seems to have (24th May) been reverted somehow somewhere down the line.
Reopening issue, propose (*breaking change*) to change out existing  `createNewCategoricalMarket(signer, title,description, oracle, end, creationType, categories, callback?)` for object paramaters, so that the first form will cease to work.
